export interface CompanyOverview {
    Symbol: string
    AssetType: string
    Name: string
    Description: string
    CIK: string
    Exchange: string
    Currency: string
    Country: string
    Sector: string
    Industry: string
    Address: string
    FiscalYearEnd: string
    LatestQuarter: string
    MarketCapitalization: string
    EBITDA: number
    PERatio: number
    PEGRatio: number
    BookValue: number
    DividendPerShare: number
    DividendYield: string
    EPS: number
    RevenuePerShareTTM: number
    ProfitMargin: number
    OperatingMarginTTM: number
    ReturnOnAssetsTTM: number
    ReturnOnEquityTTM: number
    RevenueTTM: number
    GrossProfitTTM: number
    DilutedEPSTTM: number
    QuarterlyEarningsGrowthYOY: number
    QuarterlyRevenueGrowthYOY: number
    AnalystTargetPrice: number
    TrailingPE: number
    ForwardPE: number
    PriceToSalesRatioTTM: number
    PriceToBookRatio: number
    EVToRevenue: number
    EVToEBITDA: number
    Beta: number
    WeekHigh52: number
    WeekLow52: number
    MovingAverage50: number
    MovingAverage200: number
    SharesOutstanding: number
    DividendDate: string
    ExDividendDate: string
  }
  